export const CUISINES = [
  "None",
  "Asian",
  "Thai",
  "Nepalese",
  "Karnataka",
  "South Indian Recipes",
  "Kashmiri",
  "Middle Eastern",
  "Fusion",
  "Uttar Pradesh",
  "Arab",
  "Coorg",
  "North Indian Recipes",
  "Maharashtrian Recipes",
  "Pakistani",
  "Chinese",
  "Hyderabadi",
  "Chettinad",
  "North Karnataka",
  "Andhra",
  "Sri Lankan",
  "African",
  "Assamese",
  "Jharkhand",
  "Bihari",
  "North East India Recipes",
  "Afghan",
  "Malvani",
  "Punjabi",
  "Mangalorean",
  "Sichuan",
  "Kongunadu",
  "Indo Chinese",
  "Mughlai",
  "Goan Recipes",
  "Tamil Nadu",
  "Kerala Recipes",
  "Bengali Recipes",
  "Uttarakhand-North Kumaon ",
  "Haryana",
  "Indian",
  "Lucknowi",
  "Malabar",
  "Oriya Recipes",
  "Gujarati Recipes\ufeff",
  "Continental",
  "Rajasthani",
  "Konkan",
  "Sindhi",
  "Parsi Recipes",
  "Himachal",
  "Awadhi",
  "Udupi",
  "South Karnataka",
  "Nagaland",
  "Coastal Karnataka"
];

export const COURSES = [
  "None",
  "One Pot Dish",
  "Lunch",
  "Snack",
  "Side Dish",
  "North Indian Breakfast",
  "South Indian Breakfast",
  "Appetizer",
  "Main Course",
  "World Breakfast",
  "Dessert",
  "Brunch",
  "Dinner",
  "Indian Breakfast"
];

export const DIET = [
  "None",
  "High Protein Vegetarian",
  "Vegan",
  "High Protein Non Vegetarian",
  "Diabetic Friendly",
  "Vegetarian",
  "No Onion No Garlic (Sattvic)",
  "Non Vegeterian",
  "Gluten Free",
  "Eggetarian"
];